<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Generated by Larastart
| andrealeixo.com - 2017
|
*/

Route::get('/', function () {
    return view('larastart-welcome');
});

/**
 * Routes for post
 */
Route::get('post/', 'PostController@getAll');
Route::get('post/{id}', 'PostController@getById')->where(':id', '[0-9]+');
Route::post('post', 'PostController@create');
Route::put('post/{id}', 'PostController@update')->where(':id', '[0-9]+');
Route::patch('post/{id}', 'PostController@patch')->where(':id', '[0-9]+');
Route::delete('post/{id}', 'PostController@destroy')->where(':id', '[0-9]+');

/**
 * Routes for author
 */
Route::get('author/', 'AuthorController@getAll');
Route::get('author/{id}', 'AuthorController@getById')->where(':id', '[0-9]+');
Route::post('author', 'AuthorController@create');
Route::put('author/{id}', 'AuthorController@update')->where(':id', '[0-9]+');
Route::patch('author/{id}', 'AuthorController@patch')->where(':id', '[0-9]+');
Route::delete('author/{id}', 'AuthorController@destroy')->where(':id', '[0-9]+');

/**
 * Routes for post
 */
Route::get('post/', 'PostController@getAll');
Route::get('post/{id}', 'PostController@getById')->where(':id', '[0-9]+');
Route::post('post', 'PostController@create');
Route::put('post/{id}', 'PostController@update')->where(':id', '[0-9]+');
Route::patch('post/{id}', 'PostController@patch')->where(':id', '[0-9]+');
Route::delete('post/{id}', 'PostController@destroy')->where(':id', '[0-9]+');

/**
 * Routes for author
 */
Route::get('author/', 'AuthorController@getAll');
Route::get('author/{id}', 'AuthorController@getById')->where(':id', '[0-9]+');
Route::post('author', 'AuthorController@create');
Route::put('author/{id}', 'AuthorController@update')->where(':id', '[0-9]+');
Route::patch('author/{id}', 'AuthorController@patch')->where(':id', '[0-9]+');
Route::delete('author/{id}', 'AuthorController@destroy')->where(':id', '[0-9]+');

/**
 * Routes for post
 */
Route::get('post/', 'PostController@getAll');
Route::get('post/{id}', 'PostController@getById')->where(':id', '[0-9]+');
Route::post('post', 'PostController@create');
Route::put('post/{id}', 'PostController@update')->where(':id', '[0-9]+');
Route::patch('post/{id}', 'PostController@patch')->where(':id', '[0-9]+');
Route::delete('post/{id}', 'PostController@destroy')->where(':id', '[0-9]+');

/**
 * Routes for author
 */
Route::get('author/', 'AuthorController@getAll');
Route::get('author/{id}', 'AuthorController@getById')->where(':id', '[0-9]+');
Route::post('author', 'AuthorController@create');
Route::put('author/{id}', 'AuthorController@update')->where(':id', '[0-9]+');
Route::patch('author/{id}', 'AuthorController@patch')->where(':id', '[0-9]+');
Route::delete('author/{id}', 'AuthorController@destroy')->where(':id', '[0-9]+');
